// Code generated by Slice Machine. DO NOT EDIT.

import Homepage from './Homepage/index.svelte';
import Members from './Members/index.svelte';
import Navbar from './Navbar/index.svelte';

export const components = {
	homepage: Homepage,
	members: Members,
	navbar: Navbar
};
