// Code generated by Slice Machine. DO NOT EDIT.

import Members from './Members/index.svelte';
import Navbar from './Navbar/index.svelte';
import Welkom from './Welkom/index.svelte';

export const components = {
	members: Members,
	navbar: Navbar,
	welkom: Welkom
};
